# Generated by Django 5.0.6 on 2024-11-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
