# Generated by Django 5.0.6 on 2024-11-16 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloted',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='main.department'),
        ),
    ]
